### ISSUE TITLE
[Windows] ctrl.mouse_click(...) api not fully implemented

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#11]
1. The times parameter seems to be ignored. Typing the following into repl should e.g. select the line of text where the mouse is located in an Editor or text box.

    talon.ctrl.mouse_click(button=0, times=3)

2. Specifying the x,y coordinates has no affect. Always clicks wherever the mouse happens to be located. Repro = type the following commands into repl and observe
   talon.ctrl.mouse_click(0,0, button=0)
   talon.ctrl.mouse_click(200,200, button=0)

**Comment by lunixbochs** [comment]
1. Times is not to actually click that many times, it is to tell the OS that your click should be registered as an nth click. To click n times you should do a times=1 click, then a times=2 click, etc.
2. If you watch the log, it should actually warn the first time you use x/y as "deprecated". It turns out you basically always need to move the mouse before clicking. This is a limitation of the underlying apps/OS.

**Comment by knausj85** [comment]
Ah, gotcha. Thanks. Closing this out.
