### ISSUE TITLE
linux pulseaudio: talon receives quieter input from stereo -> mono downmixing

### ISSUE THREAD

**Issue by faithanalog** [talonvoice/beta#57]
My sound card provides a stereo input to my computer, but my microphone is only on the left channel. When talon requests this as a mono input, it gets downmixed by pulseaudio, so you get a -6db reduction in volume. This might apply to other platforms as well- im unsure.

could make sense for talon to instead request a stereo stream, and pick whichever channel is active.

right now you can compensate for this by increasing the gain for talon's input in pavucontrol

**Comment by gimpf** [comment]
It should be -3dB, not -6dB, although some USB audio IFs seems to have a separate issue where this can happen.

You can use PulseAudio for a work-around: https://github.com/gimpf/talon-config/blob/master/utils/setup-microphone.sh

No increasing gain necessary.

Please note that depending on how stuff is plugged in, it could also be any other channel carrying the mic.

**Comment by lunixbochs** [comment]
can anyone confirm the behavior on recent talon, e.g. 1422?

**Comment by gimpf** [comment]
Summary: It works. I just tested this with version 1425.

No software-induced clipping (the Focusrite Scarlett problem), and no -3 dB gain (the math problem) anymore. The recordings sound clear w/o artifacts and have the correct sound level. They only clip when my audio IF itself shows the clipping warning, so HW and SW agree.

There is only one word of warning to people who use pavucontrol to check their gain in real-time: The display is now useless. Because the sound-level meter of pavucontrol is not only linear as I just learned (wtf???), but also, of course, shows the _stereo_ soundlevel. So it can ever only max out at half the bar. There is no mark, of course, just eyeballing.

So: use Audacity (w/stereo input!), or listen to the recordings, as we should always do anyway.
